"""Project-wide constants."""

from bassos.minigame_defaults import MINIGAME_USER_SETTINGS_DEFAULTS

EVENT_HEADERS = [
    "event_id",
    "created_at",
    "start_at",
    "end_at",
    "duration_min",
    "event_type",
    "activity",
    "xp",
    "title",
    "notes",
    "song_library_id",
    "drill_id",
    "quest_id",
    "achievement_id",
    "tags",
    "evidence_type",
    "evidence_path",
    "evidence_url",
    "meta_json",
    "source",
]

ACHIEVEMENT_EXTRA_HEADERS = ["is_hidden", "hint", "auto_grant", "ui_badge_style"]

ACHIEVEMENT_HEADERS = [
    "achievement_id",
    "group_id",
    "name",
    "tier",
    "tier_name",
    "category",
    "rarity",
    "rule_type",
    "rule_filter",
    "target",
    "display_order",
    "xp_reward",
    "description",
    "evidence_hint",
    "is_hidden",
    "hint",
    "auto_grant",
    "ui_badge_style",
    "icon_path",
    "icon_url",
]

QUEST_HEADERS = [
    "quest_id",
    "title",
    "emoji",
    "description",
    "status",
    "xp_reward",
    "start_date",
    "due_date",
    "period_class",
    "difficulty",
    "priority",
    "auto_generated",
    "resolved_at",
    "genre_tags",
    "linked_song_ids",
    "linked_drill_ids",
    "rule_type",
    "rule_filter",
    "target",
    "source",
]

# Legacy quest columns are intentionally deprecated in the new quest model.
QUEST_EXTRA_HEADERS: list[str] = []

DRILL_LIBRARY_HEADERS = [
    "drill_id",
    "name",
    "description",
    "area",
    "favorite",
    "tags",
    "bpm_min",
    "bpm_max",
    "bpm_step",
    "default_backing_id",
    "image_path",
    "image_paths",
    "image_url",
    "resource",
    "notes",
    "created_at",
    "last_used_at",
]

BACKING_TRACK_HEADERS = [
    "backing_id",
    "title",
    "description",
    "genre",
    "favorite",
    "chords",
    "bpm",
    "youtube_url",
    "drill_id",
    "tags",
    "notes",
    "created_at",
    "last_used_at",
]

RECORD_POST_HEADERS = [
    "post_id",
    "created_at",
    "updated_at",
    "title",
    "body",
    "post_type",
    "header_id",
    "template_id",
    "meta_json",
    "tags",
    "linked_song_ids",
    "linked_drill_ids",
    "free_targets",
    "legacy_event_id",
    "source",
]

RECORD_ATTACHMENT_HEADERS = [
    "attachment_id",
    "post_id",
    "created_at",
    "media_type",
    "path",
    "url",
    "title",
    "notes",
    "sort_order",
]

RECORD_COMMENT_HEADERS = [
    "comment_id",
    "post_id",
    "parent_comment_id",
    "created_at",
    "updated_at",
    "body",
    "deleted",
    "source",
]

SONG_LIBRARY_HEADERS = [
    "library_id",
    "song_id",
    "title",
    "artist",
    "genre",
    "mood",
    "difficulty",
    "favorite",
    "purpose",
    "status",
    "focus_section",
    "goal_bpm",
    "key",
    "original_url",
    "sub_urls",
    "cover_path",
    "score_pdf_path",
    "score_image_paths",
    "cover_url",
    "best_take_path",
    "best_take_url",
    "tags",
    "notes",
    "created_at",
    "last_practiced_at",
]

TUTORIAL_CAMPAIGN_ID = "core_v1"
TUTORIAL_REWARD_XP = 60
TUTORIAL_TITLE_ID = "guide_finisher"

DASHBOARD_LAYOUT_LEGACY_DEFAULT = {
    "hud": {"x": 1, "y": 1, "w": 1, "h": 1, "visible": True},
    "timer": {"x": 2, "y": 1, "w": 1, "h": 1, "visible": True},
    "progress": {"x": 1, "y": 2, "w": 2, "h": 1, "visible": True},
    "nextWin": {"x": 3, "y": 3, "w": 1, "h": 1, "visible": True},
    "photo": {"x": 3, "y": 1, "w": 1, "h": 2, "visible": True},
    "songShortcut": {"x": 1, "y": 3, "w": 2, "h": 1, "visible": True},
    "achievements": {"x": 1, "y": 4, "w": 2, "h": 1, "visible": False},
}

DASHBOARD_LAYOUT_FOCUS_DEFAULT = {
    "hud": {"x": 1, "y": 1, "w": 1, "h": 1, "visible": True},
    "timer": {"x": 2, "y": 1, "w": 1, "h": 1, "visible": True},
    "nextWin": {"x": 3, "y": 4, "w": 1, "h": 1, "visible": True},
    "progress": {"x": 1, "y": 2, "w": 2, "h": 1, "visible": True},
    "photo": {"x": 3, "y": 1, "w": 1, "h": 3, "visible": True},
    "songShortcut": {"x": 1, "y": 3, "w": 2, "h": 1, "visible": True},
    "achievements": {"x": 1, "y": 4, "w": 2, "h": 1, "visible": True},
}


JOURNAL_HEADER_CATALOG_DEFAULTS = [
    {"id": "daily_practice", "label": "일일연습", "color": "#496f6a", "active": True, "order": 0},
    {"id": "monthly_review", "label": "월간회고", "color": "#7b6c55", "active": True, "order": 1},
    {"id": "video_review", "label": "영상회고", "color": "#5b6f93", "active": True, "order": 2},
    {"id": "performance", "label": "합주/공연", "color": "#8c6656", "active": True, "order": 3},
    {"id": "idea", "label": "아이디어", "color": "#6c5a88", "active": True, "order": 4},
    {"id": "archive", "label": "자료정리", "color": "#5c6e7c", "active": True, "order": 5},
]

JOURNAL_TEMPLATE_CATALOG_DEFAULTS = [
    {
        "id": "daily_log",
        "name": "일일 연습 일지",
        "description": "하루 연습 내용을 빠르게 기록합니다.",
        "header_id": "daily_practice",
        "default_tags": ["일일연습"],
        "body_markdown": "## 오늘의 포커스\n- \n\n## 잘 된 점\n- \n\n## 막힌 점\n- \n\n## 다음 액션\n- [ ] \n",
        "active": True,
        "order": 0,
    },
    {
        "id": "monthly_review",
        "name": "한 달 연습 회고",
        "description": "월 단위 회고와 다음 달 계획을 정리합니다.",
        "header_id": "monthly_review",
        "default_tags": ["월간회고"],
        "body_markdown": "## 이번 달 요약\n- \n\n## 가장 늘어난 점\n- \n\n## 아직 불안한 점\n- \n\n## 다음 달 목표\n- [ ] \n",
        "active": True,
        "order": 1,
    },
    {
        "id": "video_review",
        "name": "영상 회고",
        "description": "촬영본을 보고 문제점과 다음 수정 포인트를 남깁니다.",
        "header_id": "video_review",
        "default_tags": ["영상회고"],
        "body_markdown": "## 체크한 구간\n- \n\n## 톤/리듬 메모\n- \n\n## 수정 포인트\n- \n\n## 다음 테이크 액션\n- [ ] \n",
        "active": True,
        "order": 2,
    },
]


SETTINGS_DEFAULTS = {
    "policy_version": 18,
    "ui": {
        "default_theme": "midnight",
        "enable_confetti": True,
        "animation_intensity": "adaptive",
        "language": "ko",
        "practice_video_pip_mode": "mini",
        "practice_video_tab_switch_playback": "continue",
        "session_timer_pip_corner": "bottom-right",
        "notify_level_up": True,
        "notify_achievement_unlock": True,
        "notify_quest_complete": True,
        "fx_level_up_overlay": True,
        "fx_achievement_unlock": True,
        "fx_quest_complete": True,
        "fx_session_complete_normal": True,
        "fx_session_complete_quick": False,
        "fx_claim_achievement": True,
        "fx_claim_quest": True,
        "dashboard_glass_cards": True,
        "dashboard_version": "focus",
        "keyboard_shortcuts": {
            "bindings": {
                "tab_dashboard": {"code": "Digit1", "alt": True},
                "tab_practice": {"code": "Digit2", "alt": True},
                "tab_gallery": {"code": "Digit3", "alt": True},
                "tab_songs": {"code": "Digit4", "alt": True},
                "tab_drills": {"code": "Digit5", "alt": True},
                "tab_recommend": {"code": "Digit6", "alt": True},
                "tab_review": {"code": "Digit7", "alt": True},
                "tab_xp": {"code": "Digit8", "alt": True},
                "tab_sessions": {"code": "Digit9", "alt": True},
                "tab_quests": {"code": "KeyQ", "alt": True},
                "tab_achievements": {"code": "KeyA", "alt": True},
                "tab_tools": {"code": "KeyB", "alt": True},
                "tab_settings": {"code": "Digit0", "alt": True},
                "video_toggle": {"code": "Space"},
                "video_restart": {"code": "KeyR"},
                "video_fullscreen": {"code": "KeyF"},
                "video_pin_save": {"code": "KeyP", "alt": True},
                "video_pin_jump": {"code": "KeyH"},
                "video_pin_clear": {"code": "KeyP", "alt": True, "shift": True},
                "score_zoom": {"code": "KeyG"},
                "score_prev": {"code": "ArrowLeft"},
                "score_next": {"code": "ArrowRight"},
                "metronome_toggle": {"code": "KeyM"},
                "pip_video_toggle": {"code": "KeyV"},
                "pip_collapse_toggle": {"code": "KeyC"},
                "pip_open_studio": {"code": "KeyS"},
                "pip_stop_session": {"code": "KeyX", "shift": True},
                "popup_primary": {"code": "Enter"},
                "popup_close": {"code": "Escape"},
                "popup_destructive": {"code": "Delete"},
                "popup_alternate": {"code": "KeyT"},
            }
        },
        "dashboard_layout_legacy": DASHBOARD_LAYOUT_LEGACY_DEFAULT,
        "dashboard_layout_focus": DASHBOARD_LAYOUT_FOCUS_DEFAULT,
        "song_genres": [
            "Rock",
            "Punk Rock",
            "Alt Rock",
            "Hard Rock",
            "Metal",
            "Funk",
            "Jazz",
            "Fusion",
            "R&B",
            "Soul",
            "Hip-hop",
            "Pop",
            "City Pop",
            "Ballad",
            "Disco",
            "Blues",
            "Latin",
            "World",
        ],
        "achievement_card_styles": {
            "tier_bronze": {"border": "#b88746", "fill": "#f8f1e7"},
            "tier_silver": {"border": "#8ca0ad", "fill": "#eff4f7"},
            "tier_gold": {"border": "#d6aa2d", "fill": "#fcf6e7"},
            "tier_platinum": {"border": "#58a4be", "fill": "#e8f7fa"},
            "tier_diamond": {"border": "#6f72ff", "fill": "#f0f0ff"},
            "tier_master": {"border": "#ff9640", "fill": "#fff1e2"},
            "single_event": {"border": "#4f8b92", "fill": "#ebf6f8"},
            "single_hidden": {"border": "#59606a", "fill": "#f0f2f5"},
        },
    },
    "audio": {
        "enabled": False,
        "master_volume": 0.6,
        "levelup_sound": "media/sfx_levelup.mp3",
    },
    "critical": {
        "backfill_multiplier_default": 0.5,
        "max_backup_files": 3,
        "backup_min_hours": 12,
        "achievement_xp_multiplier": 0.15,
        "quest_xp_multiplier": 0.15,
        "session_xp_multiplier": 1.0,
        "daily_session_xp_cap": 0,
    },
    "admin": {
        "gate_enabled": False,
        "pin_hash": "",
    },
    "backup": {
        "enabled": True,
        "max_files": 3,
        "min_hours_between": 12,
    },
    "performance": {
        "target_dashboard_ms": 1000,
    },
    "profile": {
        "nickname": "",
        "weekly_goal_sessions": 3,
        "onboarded": False,
        "quest_settings": {
            "period_days": {"short": 7, "mid": 30, "long": 90},
            "auto_enabled_by_period": {"short": True, "mid": True, "long": True},
            "auto_target_minutes_by_period": {"short": 120, "mid": 360, "long": 900},
            "auto_priority_by_period": {"short": "normal", "mid": "normal", "long": "urgent"},
            "auto_difficulty_by_period": {"short": "low", "mid": "mid", "long": "high"},
            "ui_style": {
                "period_border": {"short": "#44728a", "mid": "#5e6f8f", "long": "#6e5f8d"},
                "period_fill": {"short": "#e7f5ff", "mid": "#eef2ff", "long": "#f4efff"},
                "priority_border": {"urgent": "#d8664a", "normal": "#4f8bc4", "low": "#6b8892"},
                "difficulty_fill": {"low": "#eef8f5", "mid": "#eef2ff", "high": "#fff0f1"},
            },
        },
        "guide_finisher_unlocked": False,
        "tutorial_state": {
            "campaign_id": TUTORIAL_CAMPAIGN_ID,
            "banner_seen_campaigns": [],
            "completed_campaigns": [],
            "reward_claimed_campaigns": [],
            "resume_campaign_id": "",
            "resume_step_index": 0,
            "last_started_at": "",
            "last_completed_at": "",
        },
        "dashboard_photo_items": [],
        "dashboard_featured_photo_id": "",
        "dashboard_photo_anchor": "center",
        "journal_tag_catalog": [],
        "journal_header_catalog": JOURNAL_HEADER_CATALOG_DEFAULTS,
        "journal_template_catalog": JOURNAL_TEMPLATE_CATALOG_DEFAULTS,
    },
    "practice_tools": {
        "minigame_user_settings": MINIGAME_USER_SETTINGS_DEFAULTS,
    },
}

XP_BALANCE_V2 = {
    # Session XP is now fixed at 3 points per minute.
    "session": {"per_min": 3},
    # Point -> display XP scale. e.g. 20,000 points = 1,000,000 XP.
    "display_scale": 50,
    "bonus": {
        "core_warmup": 8,
        "metronome_24": 6,
        "metronome_onebar": 12,
        "recording_audio": 14,
        "recording_video": 16,
        "earcopy": 14,
        "theory": 10,
        "slap": 10,
        "clean_mute": 8,
        "ab_compare": 12,
    },
    "weekly_chest": {"xp": 180},
    "monthly_long_goal": {"song_fulltake": 650, "earcopy_full": 900},
    "rehearsal_bonus": 16,
    "performance_bonus": 48,
    "backfill_multiplier": 0.5,
}

# Target milestones: fast onboarding, slower late game with decade step-ups.
LEVEL_BALANCE_V2 = {
    "type": "decade_linear",
    "base": 174,
    "slope": 4,
    "step_10": 40,
    "step_20": 90,
    "step_30": 200,
    "step_40": 347,
    "max_level": 50,
}

ACTIVITY_TO_TAG = {
    "Song": "SONG",
    "Drill": "DRILL",
    "Etc": "ETC",
    "Core": "CORE",
    "Funk&Jazz": "FUNKJAZZ",
    "Theory": "THEORY",
    "Slap": "SLAP",
    "SongCopy": "SONG_COPY",
    "SongPractice": "SONG_PRACTICE",
    "Band": "BAND",
    "Performance": "PERFORMANCE",
    "Community": "COMMUNITY",
    "Gear": "GEAR",
}

SUB_ACTIVITY_TO_TAG = {
    "SongCopy": "SONG_COPY",
    "SongLearn": "SONG_LEARN",
    "SongPractice": "SONG_PRACTICE",
    "Core": "CORE",
    "Funk": "FUNK",
    "Slap": "SLAP",
    "Theory": "THEORY",
    "SongDiscovery": "SONG_DISCOVERY",
    "Community": "COMMUNITY",
    "Gear": "GEAR",
    "Etc": "ETC",
}

CHECKBOX_TAG_TO_BONUS_KEY = {
    "METRO_24": "metronome_24",
    "METRO_ONEBAR": "metronome_onebar",
    "CLEAN_MUTE": "clean_mute",
    "EAR_COPY": "earcopy",
    "RECORDING_AUDIO": "recording_audio",
    "RECORDING_VIDEO": "recording_video",
    "AB_COMPARE": "ab_compare",
    "THEORY": "theory",
    "SLAP": "slap",
    "CORE": "core_warmup",
}
